name: CICD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Code Compile
      run: mvn compile
    - name: Code Test
      run: mvn test
    - name: Code Build
      run: mvn package
    - name: Trivy Scan
      run: trivy fs --format table -o trivy-scaner-report.html .
    - name: Build and Analyze with SonarCloud
      run: mvn clean verify org.sonarsource.scanner.maven:sonar -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} -Dsonar.login=${{ secrets.SONAR_TOKEN }}
